version: '3.9'
services:
  discord-img-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-img-bot
    environment:
      - TOKEN=${TOKEN}
      - RUNNERS=${RUNNERS:-2}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
